composers:
  git_clone: JustCompose.Composers.GitClone.GitCloneComposer, JustCompose.Composers.GitClone
  script: JustCompose.Composers.Script.ScriptComposer, JustCompose.Composers.Script

compositions:
  ci:
    description: Run tests during CI
    steps:
      clone:
        composer: git_clone
        properties:
          clone_url: https://github.com/JeevanJames/Id3
          clone_directory: D:\Temp\Id3
      build:
        composer: script
        properties:
          inline_script: |
            @echo off
            d:
            cd \Temp\Id3
            dotnet build -c Release
      second_script:
        composer: script
        properties:
          script_type: Powershell
          inline_script: |
            Write-Host 'Hello World!'
            Write-Host 'Second line'
  local:
    description: Run tests locally
    steps:
      first_script:
        composer: script
        properties:
          script_type: Powershell
          inline_script: Write-Host 'Local script'
