composers:
  script: JustCompose.Composers.Script.ScriptComposer, JustCompose.Composers.Script

compositions:
  ci:
    description: Run tests during CI
    steps:
      first_script:
        composer: script
        properties:
          inline_script: |
            @echo off
            d:
            cd \Code\GitHub\IniFile
            dotnet build -c Release
          async: true
      second_script:
        composer: script
        properties:
          script_type: Powershell
          inline_script: |
            Write-Host 'Hello World!'
            Write-Host 'Second line'
  local:
    description: Run tests locally
    steps:
      first_script:
        composer: script
        properties:
          script_type: Powershell
          inline_script: Write-Host 'Local script'
